# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_modular_headers!

target 'RNSnowplowTracker' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

  # Pods for RNSnowplowTracker
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native'
  pod 'SnowplowTracker', '~> 1.6.2'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end
